export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "on-surface-variant": "#434843",
        "on-background": "#1b1c19",
        secondary: "#536257",
        "primary-fixed": "#d0e9d4",
        "error-container": "#ffdad6",
        surface: "#fbf9f4",
        "surface-dim": "#dbdad5",
        "secondary-fixed": "#d6e7d8",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#261900",
        "inverse-primary": "#b4cdb8",
        outline: "#737973",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#5d4201",
        "on-surface": "#1b1c19",
        "on-secondary-fixed": "#111f16",
        "surface-container-highest": "#e4e2dd",
        "on-primary-fixed": "#0b2013",
        "on-secondary-container": "#59685c",
        "surface-variant": "#e4e2dd",
        "surface-bright": "#fbf9f4",
        "on-secondary-fixed-variant": "#3b4a40",
        "primary-container": "#1b3022",
        "tertiary-container": "#3a2800",
        "on-error-container": "#93000a",
        "surface-container-low": "#f5f3ee",
        "on-primary-fixed-variant": "#364c3c",
        "inverse-surface": "#30312e",
        "surface-tint": "#4d6453",
        "on-primary-container": "#819986",
        "surface-container-high": "#eae8e3",
        "secondary-fixed-dim": "#bacbbd",
        "inverse-on-surface": "#f2f1ec",
        "surface-container": "#f0eee9",
        "on-tertiary-container": "#b18d48",
        "tertiary-fixed-dim": "#e9c176",
        tertiary: "#211500",
        "on-primary": "#ffffff",
        primary: "#061b0e",
        "secondary-container": "#d6e7d8",
        "primary-fixed-dim": "#b4cdb8",
        "on-error": "#ffffff",
        "outline-variant": "#c3c8c1",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdea5",
        background: "#fbf9f4",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        serif: ["Noto Serif", "serif"],
      },
      fontSize: {
        'display-lg': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-md': ['2.8rem', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
      }
    },
  },
  plugins: [],
}
